# Generated by Django 5.2.1 on 2025-05-27 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabana',
            fields=[
                ('id_cabana', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=100)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(default='Disponible', max_length=20)),
            ],
            options={
                'db_table': 'cabanas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_item', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.IntegerField()),
                ('ubicacion', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('id_reserva', models.IntegerField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(default='Transferencia', max_length=30)),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('id_cabana', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
            ],
            options={
                'db_table': 'reservas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('contrasena', models.CharField(max_length=100)),
                ('rol', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
    ]
