# Generated by Django 5.2.1 on 2025-06-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_comentario_mensajecontacto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': True},
        ),
    ]
