# Generated by Django 5.2.1 on 2025-06-12 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_reserva_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'managed': False},
        ),
    ]
